##################################################
# Run Super-Linter for Java Codebase #
##################################################

name: Mr Coxall's Super Linter

on: [push, pull_request]

jobs:
  run-linters:
    name: Java Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run GitHub Super Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          LINTER_RULES_PATH: /
          VALIDATE_JAVA: true  # Enable Java linting
          VALIDATE_GOOGLE_JAVA_FORMAT: true  # Use Google Java Format
          VALIDATE_CHECKSTYLE: true  # Run Checkstyle
          VALIDATE_PMD: false  # Set to true if you want PMD checks
          VALIDATE_SPOTBUGS: false  # Set to true if you want static analysis
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
