##################################################
# Run Super-Linter for Java Codebase #
##################################################

name: Mr Coxall's Super Linter

on: [push, pull_request]

jobs:
  run-linters:
    name: Mr Coxall's Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2 🚦

      - name: Run GitHub Super Linter 🚀
        uses: mr-coxall/super-linter@master
        env:
          VALIDATE_ALL_CODEBASE: true
          LINTER_RULES_PATH: /
          VALIDATE_JAVA: true
          VALIDATE_GOOGLE_JAVA_FORMAT: false
          VALIDATE_CHECKSTYLE: true
          VALIDATE_PMD: false
          VALIDATE_SPOTBUGS: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Checkstyle with custom configuration
        uses: jwgmeligmeyling/checkstyle-action@v1
        with:
          checkstyle_config: '.github/checkstyle.xml'  # Path to your custom checkstyle.xml
          fail_on_error: false  # Set to true if you want the build to fail on Checkstyle errors
